### ISSUE TITLE
firestore-emulator/javascript-quickstart doesn't pass tests

### ISSUE THREAD

**Issue by kevlened** [firebase/quickstart-nodejs#36] opened 2018-11-22 00:07 UTC
I'm unsure if this is related to #35, but here are the repro steps:

```bash
$ firebase --version
6.1.1

$ node -v
v8.12.0

$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

$ git clone git@github.com:firebase/quickstart-nodejs.git
$ cd quickstart-nodejs/firestore-emulator/javascript-quickstart/
$ npm install

$ firebase setup:emulators:firestore
i  firestore: downloading emulator...
$ firebase serve --only firestore
✔  firestore: started on http://localhost:8080
⚠  firestore: Nov 21, 2018 4:03:40 PM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
INFO: Unable to apply Java 7 long hostname workaround.

Dev App Server is now running.


API endpoint: http://localhost:8080

$ npm test
> cloud-firestore-emulator-javascript-quickstart@1.0.1 test quickstart-nodejs/firestore-emulator/javascript-quickstart
> mocha

(node:47062) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
  My app
    ✓ require users to log in before creating a profile (645ms)
    ✓ should enforce the createdAt date in user profiles (229ms)
    ✓ should only let users create their own profile (60ms)
    1) "before each" hook for "should let anyone read any profile"

  3 passing (5s)
  1 failing

  1) "before each" hook for "should let anyone read any profile":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Here are the logs for the firestore emulator:
```
⚠  firestore: Nov 21, 2018 4:11:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'create' @ L5, Null value error. for 'create' @ L5

⚠  firestore: Nov 21, 2018 4:11:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Property createdAt is undefined on object. for 'create' @ L5, Property createdAt is undefined on object. for 'create' @ L5

⚠  firestore: Nov 21, 2018 4:11:19 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L5
```

**Comment by ryanpbrewster** [comment] 2018-11-28 04:59
This is a timeout caused by https://github.com/firebase/firebase-js-sdk/issues/1396

The next release of `@firebase/testing` should resolve this. For now I've merged https://github.com/firebase/quickstart-nodejs/pull/43 to work around this issue.

**Closed** 2018-11-28 05:00 UTC
